{% set name = "getfem" %}
{% set version = "5.4.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://download-mirror.savannah.gnu.org/releases/{{ name }}/stable/{{ name }}-{{ version }}.tar.gz
  sha256: 52795d577953cd1a96bb9e55fdf426bf6a042f59b08c02accf2726d2476ce4dd

build:
  number: 0
  skip: true  # [win or osx or (python_impl == 'pypy')]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - libtool
    - make
    - python
    - numpy
    - scipy
    - qhull
    - mumps-seq
    - libopenblas
  run:
    - numpy
    - scipy
    - qhull
    - mumps-seq
    - libopenblas
    - python

test:
  imports:
    - getfem

about:
  home: https://getfem.org/
  license: LGPL-3.0-or-later AND BSD-3-Clause
  license_family: LGPL
  license_file:
    - COPYING
    - dep-licenses/
  summary: 'GetFEM++ is a generic finite element C++ library with interfaces for Python, Matlab and Scilab.'
  description: |
    The GetFEM project focuses on the development of a generic and efficient C++ library for finite element methods elementary computations.
  doc_url: https://getfem.readthedocs.io
  dev_url: https://github.com/getfem-doc/getfem

extra:
  recipe-maintainers:
    - logari81
    - yvesrenard
    - tkoyama010
    - daviddanan
    - ldallolio
